name: cut release

on:
    workflow_dispatch:
        inputs:
            version:
                description: Semver version of the release
                required: true

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
    test-and-build:
        runs-on: ubuntu-latest
        steps:
            - name: Print semver version
              run: echo Version ${{ inputs.version }}
            - name: Checkout main
              uses: actions/checkout@main
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: 16
            - name: Generate .npmrc
              run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            - name: Install Dependencies
              run: yarn
            - name: Check Unit Tests
              run: yarn test
            - name: Verify it builds
              run: yarn build
            - name: Release Version
              run: yarn release-it --npm.skipChecks -i ${{ inputs.version }}
