name: cut release

on:
    workflow_dispatch:
        inputs:
            version:
                description: Semver version of the release
                required: true

jobs:
    test-and-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                node-version: 16
            - run: yarn
            - run: yarn test
            - run: yarn build
            - name: Release Version
            - run: yarn release-it -i ${{ github.version }}
