name: cut release

on:
    workflow_dispatch:
        inputs:
            version:
                description: Semver version of the release
                required: true

jobs:
    test-and-build:
        runs-on: ubuntu-latest
        steps:
            - name: Print semver version
              run: echo Version ${{ inputs.version }}
            - name: Checkout main
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: git config
              run: |
                git config user.name "${GITHUB_ACTOR}"
                git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: 16
            - name: Setup NPM Registry
              run: npm set //npm.pkg.github.com/:_authToken $NPM_TOKEN
              env:
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Install Dependencies
              run: yarn
            - name: Check Unit Tests
              run: yarn test
            - name: Verify it builds
              run: yarn build
            - name: Release Version
              run: yarn release-it -i ${{ inputs.version }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
