name: Cut Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: Semver version of the release
                required: true

jobs:
    test-and-build:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v1
          with:
            node-version: 16
        - run: yarn
        - run: yarn test
        - run: yarn build
        - run: yarn release-it -i ${{ github.version }}
